import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


GROUPS = [
    ("Volumes", ["V_RA", "V_RV", "V_P", "V_LA", "V_LV", "V_AO", "V_V"], "Volume [mL]"),
    ("Pressures", ["P_RA", "P_RV", "P_P", "P_LA", "P_LV", "P_AO", "P_V"], "Pressure"),
    ("Flows", ["Q_RA", "Q_RV", "Q_P", "Q_LA", "Q_LV", "Q_AO", "Q_V"], "Flow"),
    ("Elastances", ["e_LV", "e_RV"], "Elastance"),
]


def read_csv(csv_path):
    with csv_path.open(newline="") as file:
        reader = csv.DictReader(file)
        fieldnames = reader.fieldnames or []

        if "t" not in fieldnames:
            raise ValueError("CSV missing required column: t")

        data = {name: [] for name in fieldnames}

        for row in reader:
            for name in fieldnames:
                data[name].append(float(row[name]))

    return data


def plot_group(axis, data, title, columns, ylabel):
    times = data["t"]
    available_columns = [column for column in columns if column in data]

    for column in available_columns:
        axis.plot(times, data[column], label=column, linewidth=1.1)

    axis.set_title(title)
    axis.set_xlabel("Time [s]")
    axis.set_ylabel(ylabel)
    axis.grid(True, alpha=0.3)

    if available_columns:
        axis.legend(loc="best", fontsize="small", ncols=2)
    else:
        axis.text(0.5, 0.5, "No matching columns", ha="center", va="center", transform=axis.transAxes)


def main():
    parser = argparse.ArgumentParser(description="Plot CVS simulation output CSV.")
    parser.add_argument("--csv", default="output.csv", help="CSV file generated by ./cvs.exe.")
    parser.add_argument("--output", help="Optional path for saving the plot image.")
    parser.add_argument("--no-show", action="store_true", help="Do not open the Matplotlib plot window.")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    data = read_csv(csv_path)

    figure, axes = plt.subplots(2, 2, figsize=(14, 8), sharex=True)
    axes = axes.ravel()

    for axis, (title, columns, ylabel) in zip(axes, GROUPS):
        plot_group(axis, data, title, columns, ylabel)

    figure.suptitle(f"CVS Simulation Output: {csv_path}", fontsize=13)
    figure.tight_layout()

    if args.output:
        output_path = Path(args.output)
        figure.savefig(output_path, dpi=160)
        print(f"Saved plot to {output_path}")

    if not args.no_show:
        plt.show()


if __name__ == "__main__":
    main()
